Epmcuxda6790  observation item backend integration
abahachuk/ptushki-mobile pull request #31
Opened 2019-06-13 12:24 UTC by Leuvarden

Updated ObservationItem to display actual photos and localized descriptions from db

2019-06-16 14:31 UTC, AfanasyShevtsov requested changes

2019-06-16 14:31 UTC, AfanasyShevtsov commented on src/screens/ObservationItem/ObservationItem.js
> +  switch (locale) {
Can we move it into utils?

2019-06-17 09:34 UTC, Leuvarden commented on src/screens/ObservationItem/ObservationItem.js
> +  switch (locale) {
moved it to localization.js

2019-06-17 09:40 UTC, AfanasyShevtsov approved these changes

2019-06-17 09:49 UTC, merged